
package pe.gtdo.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ABDCPWebServicePortType", targetNamespace = "http://ws.inpac.telcordia.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ABDCPWebServicePortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns pe.gtdo.soap.ReceiveMessageResponse
     */
    @WebMethod(action = "urn:receiveMessage")
    @WebResult(name = "receiveMessageResponse", targetNamespace = "http://ws.inpac.telcordia.com", partName = "parameters")
    public ReceiveMessageResponse receiveMessage(
        @WebParam(name = "receiveMessageRequest", targetNamespace = "http://ws.inpac.telcordia.com", partName = "parameters")
        ReceiveMessageRequest parameters);

}
